# Site settings
title: Xinchejian: hackerspace in Shanghai
email: webmaster@xinchejian.com
description: > # this means to ignore newlines until "baseurl:"
  Xinchejian is a hackerspace. Hackerspaces are communities where people who are interested in physical computing and technology can meet and collaborate on projects.
  Xinchejian is the first hackerspace in China. It is a non-profit organization run by volunteers. Xinchejian’s mission is to support and promote physical computing, open source hardware, and the Internet of Things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xinchejian.com" # the base hostname & protocol for your site
twitter_username: xinchejian
github_username:  xinchejian

# Build settings
markdown: kramdown
